<br /><br />
<div id="view-content">
	<h1>Clients Management</h1>
	<p>Add new clients, find and show a client's details, update a client's details, 
		or list all the clients
	</p>
	
	<ul>
		<li><a href="http://managenonprofit.local:8080/clients/create">Create new clients</a></li>
		<li><a href="http://managenonprofit.local:8080/clients/findaclient">Find a client and show his details</a></li>
		<li><a href="http://managenonprofit.local:8080/clients/list">List the clients</a></li>	
	</ul>
</div>