<h2>The application ECaseManagement</h2>
<div>
	<p>
		Enable to manage your clients, plans they are registered in and services they need.
		Use this application to:
	</p>
	<ul>
		<li><a href="http://managenonprofit.local:8080/clients">Register new clients and modify clients records</a></li>
		<li><a href="http://managenonprofit.local:8080/needsassessments">Manage clients needs and register clients in plans.</a></li>
		<li><a href="http://managenonprofit.local:8080/plans">Manage the social plans.</a></li>
		<li><a href="http://managenonprofit.local:8080/services">Record the services they receive and the case manager working on the case</a></li>
		<li><a href="http://managenonprofit.local:8080/casemanagers">Manage the case managers of the organization</a></li>
	</ul>
</div>




