<br /><br />
<div id="view-content">
	<h1>Services Management</h1>
	<p>
		Add or update a service, and list the available services.
	</p>
	<ul>
		<li><a href="http://managenonprofit.local:8080/services/create">Add a service</a></li>
		<li><a href="http://managenonprofit.local:8080/services/findaservice">Update a service</a></li>
		<li><a href="http://managenonprofit.local:8080/services/list">List the services</a></li>
	</ul>
</div>