<br /><br />
<div id="view-content">
	<h1>Plans Management</h1>
	<p>
		Add or update Social Plans, list the existing plans
	</p>
	<ul>
		<li><a href="http://managenonprofit.local:8080/plans/create">Add a plan</a></li>
		<li><a href="http://managenonprofit.local:8080/plans/findaplan">Edit a plan</a></li>
		<li><a href="http://managenonprofit.local:8080/plans/list">List the plan</a></li>
	</ul> 
</div>