<br /><br />
<div id="view-content">
	<h1>Casemanagers Management</h1>
	<p>
		Add or update a Casemanager, view a casemanager details, list the casemanagers
	</p>
	<ul>
		<li><a href="http://managenonprofit.local:8080/casemanagers/create">Add a casemanager</a></li>
		<li><a href="http://managenonprofit.local:8080/casemanagers/update">Update a casemanager details</a></li>
		<li><a href="http://managenonprofit.local:8080/casemanagers/list">List the casemanagers</a></li>
	</ul> 
</div>

