<tr>
	<td class="links">
		<a href='/clients/update/id/<?php echo $this->id;?>'>Update</a>
		<a href='/clients/delete/id/<?php echo $this->id;?>'>Delete</a>
	</td>
	<td><?php echo $this->lastName ?></td>
	<td><?php echo $this->firstName?></td>
	<td><?php echo $this->middleName?></td>
	<td><?php echo $this->dateOfBirth?></td>
	<td><?php echo $this->street?></td>
	<td><?php echo $this->city?></td>
	<td><?php echo $this->homeType?></td>
	<td><?php echo $this->homePhone?></td>
	<td><?php echo $this->cellPhone?></td>
	<td><?php echo $this->workPhone?></td>
	<td><?php echo $this->email?></td>
	<td><?php echo $this->houseHoldSize?></td>
	<td><?php echo $this->gender?></td>
	<td><?php echo $this->maritalStatus?></td>
	<td><?php echo $this->isDependent?></td>
	<td><?php echo $this->ssn?></td>
	<td><?php echo $this->languageSpoken?></td>
	<td><?php echo $this->countryOfOrigin?></td>
	<td><?php echo $this->immigrationSatus?></td>
	<td><?php echo $this->dateOfArrival?></td>
	<td><?php echo $this->dateOfIntake?></td>
	<td><?php echo $this->alienNumber?></td>
	<td><?php echo $this->emmergencyContactName?></td>
	<td><?php echo $this->contactPhone?></td>
	<td><?php echo $this->conactPhoneType?></td>
	<td><?php echo $this->contactRelationship?></td>
</tr>